<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>A Century of Negro Migration - 2&nbsp; A Transplantation to the North</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/chapter-03.html" rel="next">
<link href="../chapters/chapter-01.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chapter-02.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">A Transplantation to the North</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">A Century of Negro Migration</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">&nbsp;</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Finding a Place of Refuge</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-02.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">A Transplantation to the North</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Fighting It Out on Free Soil</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Colonization as a Remedy for Migration</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">The Successful Migrant</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Confusing Movements</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">The Exodus to the West</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">The Migration of the Talented Tenth</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">The Exodus During the World War</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">A Transplantation to the North</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Just after the settlement of the question of holding the western posts by the British and the adjustment of the trouble arising from their capture of slaves during our second war with England, there started a movement of the blacks to this frontier territory. But, as there were few towns or cities in the Northwest during the first decades of the new republic, the flight of the Negro into that territory was like that of a fugitive taking his chances in the wilderness. Having lost their pioneering spirit in passing through the ordeal of slavery, not many of the bondmen took flight in that direction and few free Negroes ventured to seek their fortunes in those wilds during the period of the frontier conditions, especially when the country had not then undergone a thorough reaction against the Negro.</p>
<p>The migration of the Negroes, however, received an impetus early in the nineteenth century. This came from the Quakers, who by the middle of the eighteenth century had taken the position that all members of their sect should free their slaves.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> The Quakers of North Carolina and Virginia had as early as 1740 taken up the serious question of humanely treating their Negroes. The North Carolina Quakers advised Friends to emancipate their slaves, later prohibited traffic in them, forbade their members from even hiring the blacks out in 1780 and by 1818 had exterminated the institution among their communicants.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> After healing themselves of the sin, they had before the close of the eighteenth century militantly addressed themselves to the task of abolishing slavery and the slave trade throughout the world. Differing in their scheme from that of most anti-slavery leaders, they were advocating the establishment of the freedmen in society as good citizens and to that end had provided for the religious and mental instruction of their slaves prior to emancipating them.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<p>Despite the fact that the Quakers were not free to extend their operations throughout the colonies, they did much to enable the Negroes to reach free soil. As the Quakers believed in the freedom of the will, human brotherhood, and equality before God, they did not, like the Puritans, find difficulties in solving the problem of elevating the Negroes. Whereas certain Puritans were afraid that conversion might lead to the destruction of caste and the incorporation of undesirable persons into the “Body Politick,” the Quakers proceeded on the principle that all men are brethren and, being equal before God, should be considered equal before the law. On account of unduly emphasizing the relation of man to God, the Puritans “atrophied their social humanitarian instinct” and developed into a race of self-conscious saints. Believing in human nature and laying stress upon the relation between man and man, the Quakers became the friends of all humanity.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<p>In 1693 George Keith, a leading Quaker of his day, came forward as a promoter of the religious training of the slaves as a preparation for emancipation. William Penn advocated the emancipation of slaves, that they might have every opportunity for improvement. In 1695 the Quakers while protesting against the slave trade denounced also the policy of neglecting their moral and spiritual welfare.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> The growing interest of this sect in the Negroes was shown later by the development in 1713 of a definite scheme for freeing and returning them to Africa after having been educated and trained to serve as missionaries on that continent.</p>
<p>When the manumission of the slaves was checked by the reaction against that class and it became more of a problem to establish them in a hostile environment, certain Quakers of North Carolina and Virginia adopted the scheme of settling them in Northern States.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> At first, they sent such freedmen to Pennsylvania. But for various reasons this did not prove to be the best asylum. In the first place, Pennsylvania bordered on the slave States, Maryland and Virginia, from which agents came to kidnap free Negroes. Furthermore, too many Negroes were already rushing to that commonwealth as the Negroes’ heaven and there was the chance that the Negroes might be settled elsewhere in the North, where they might have better economic opportunities.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> A committee of forty was accordingly appointed by North Carolina Quakers in 1822 to examine the laws of other free States with a view to determining what section would be most suitable for colonizing these blacks. This committee recommended in its report that the blacks be colonized in Ohio, Indiana and Illinois.</p>
<p>The yearly meeting, therefore, ordered the removal of such Negroes as fast as they were willing or as might be consistent with the profession of their sect, and instructed the agents effecting the removal to draw on the treasury for any sum not exceeding two hundred dollars to defray expenses. An increasing number reached these States every year but, owing to the inducements offered by the American Colonization Society, some of them went to Liberia. When Liberia, however, developed into every thing but a haven of rest, the number sent to the settlements in the Northwest greatly increased.</p>
<p>The quarterly meeting succeeded in sending to the West 133 Negroes, including 23 free blacks and slaves given up because they were connected by marriage with those to be transplanted.[8] The Negro colonists seemed to prefer Indiana.[9] They went in three companies and with suitable young Friends to whom were executed powers of attorney to manumit, set free, settle and bind them out.[10] Thirteen carts and wagons were bought for these three companies; $1,250 was furnished for their traveling expenses and clothing, the whole cost amounting to $2,490. It was planned to send forty or fifty to Long Island and twenty to the interior of Pennsylvania, but they failed to prosper and reports concerning them stamped them as destitute and deplorably ignorant. Those who went to Ohio and Indiana, however, did well.[11]</p>
<p>Later we receive another interesting account of this exodus. David White led a company of fifty-three into the West, thirty-eight of whom belonged to Friends, five to a member who had ordered that they be taken West at his expense. Six of these slaves belonged to Samuel Lawrence, a Negro slaveholder, who had purchased himself and family. White pathetically reports the case of four of the women who had married slave husbands and had twenty children for the possession of whom the Friends had to stand a lawsuit in the courts. The women had decided to leave their husbands behind but the thought of separation so tormented them that they made an effort to secure their liberty. Upon appealing to their masters for terms the owners, somewhat moved by compassion, sold them for one half of their value. White then went West and left four in Chillicothe, twenty-three in Leesburg and twenty-six in Wayne County, Indiana, without encountering any material difficulty.[12]</p>
<p>Others had thought of this plan but the Quakers actually carried it out on a small scale. Here we see again not only their desire to have the Negroes emancipated but the vital interest of the Quakers in success of the blacks, for members of this sect not only liberated their slaves but sold out their own holdings in the South and moved with these freedmen into the North. Quakers who then lived in free States offered fugitives material assistance by open and clandestine methods.[13] The most prominent leader developed by the movement was Levi Coffin, whose daring deeds in behalf of the fugitives made him the reputed President of the Underground Railroad. Most of the Quaker settlements of Negroes with which he was connected were made in what is now Hamilton, Howard, Wayne, Randolph, Vigo, Gibson, Grant, Rush, and Tipton Counties, Indiana, and Darke County, Ohio.</p>
<p>The promotion of this movement by the Quakers was well on its way by 1815 and was not materially checked until the fifties when the operations of the drastic fugitive slave law interfered, and even then the movement had gained such momentum and the execution of that mischievous measure had produced in the North so much reaction like that expressed in the personal liberty laws, that it could not be stopped. The Negroes found homes in Western New York, Western Pennsylvania and throughout the Northwest Territory. The Negro population of York, Harrisburg and Philadelphia rapidly increased. A settlement of Negroes developed at Sandy Lake in Northwestern Pennsylvania[14] and there was another near Berlin Cross Roads in Ohio.[15] A group of Negroes migrating to this same State found homes in the Van Buren Township of Shelby County.[16] A more significant settlement in the State was made by Samuel Gist, an Englishman possessing extensive plantations in Hanover, Amherst, and Henrico Counties, Virginia. He provided in his will that his slaves should be freed and sent to the North. He further provided that the revenue from his plantation the last year of his life be applied in building schoolhouses and churches for their accommodation, and “that all money coming to him in Virginia be set aside for the employment of ministers and teachers to instruct them.” In 1818, Wickham, the executor of his estate, purchased land and established these Negroes in what was called the Upper and Lower Camps of Brown County.[17]</p>
<p>Augustus Wattles, a Quaker from Connecticut, made a settlement in Mercer County, Ohio, early in the nineteenth century. In the winter of 1833-4, he providentially became acquainted with the colored people of Cincinnati, finding there about “4,000 totally ignorant of every thing calculated to make good citizens.” As most of them had been slaves, excluded from every avenue of moral and mental improvement, he established for them a school which he maintained for two years. He then proposed to these Negroes to go into the country and purchase land to remove them “from those contaminating influences which had so long crushed them in our cities and villages.”[18] They consented on the condition that he would accompany them and teach school. He travelled through Canada, Michigan and Indiana, looking for a suitable location, and finally selected for settlement a place in Mercer County, Ohio. In 1835, he made the first purchase of land there for this purpose and before 1838 Negroes had bought there about 30,000 acres, at the earnest appeal of this benefactor, who had travelled into almost every neighborhood of the blacks in the State, and laid before them the benefits of a permanent home for themselves and of education for their children.[19]</p>
<p>This settlement was further increased in 1858 by the manumitted slaves of John Harper of North Carolina.[20] John Randolph of Roanoke endeavored to establish his slaves as freemen in this county but the Germans who had settled in that community a little ahead of them started such a disturbance that Randolph’s executor could not carry out his plan, although he had purchased a large tract of land there.[21] It was necessary to send these freemen to Miami County. Theodoric H. Gregg of Dinwiddie County, Virginia, liberated his slaves in 1854 and sent them to Ohio.[22] Nearer to the Civil War, when public opinion was proscribing the uplift of Negroes in Kentucky, Noah Spears secured near Xenia, Greene County, Ohio, a small parcel of land for sixteen of his former bondsmen in 1856.[23] Other freedmen found their way to this community in later years and it became so prosperous that it was selected as the site of Wilberforce University.</p>
<p>This transplantation extended into Michigan. With the help of persons philanthropically inclined there sprang up a flourishing group of Negroes in Detroit. Early in the nineteenth century they began to acquire property and to provide for the education of their children. Their record was such as to merit the encomiums of their fellow white citizens. In later years this group in Detroit was increased by the operation of laws hostile to free Negroes in the South in that life for this class not only became intolerable but necessitated their expatriation. Because of the Virginia drastic laws and especially that of 1838 prohibiting the return to that State of such Negro students as had been accustomed to go North to attend school, after they were denied this privilege at home, the father of Richard DeBaptiste and Marie Louis More, the mother of Fannie M. Richards, led a colony of free Negroes from Fredericksburg to Detroit.[24] And for about similar reasons the father of Robert A. Pelham conducted others from Petersburg, Virginia, in 1859.[25] One Saunders, a planter of Cabell County, West Virginia, liberated his slaves some years later and furnished them homes among the Negroes settled in Cass County, Michigan, about ninety miles east of Chicago, and ninety-five miles west of Detroit.</p>
<p>This settlement had become attractive to fugitive slaves and freedmen because the Quakers settled there welcomed them on their way to freedom and in some cases encouraged them to remain among them. When the increase of fugitives was rendered impossible during the fifties when the Fugitive Slave Law was being enforced, there was still a steady growth due to the manumission of slaves by sympathetic and benevolent masters in the South.[26] Most of these Negroes settled in Calvin Township, in that county, so that of the 1,376 residing there in 1860, 795 were established in this district, there being only 580 whites dispersed among them. The Negro settlers did not then obtain control of the government but they early purchased land to the extent of several thousand acres and developed into successful small farmers. Being a little more prosperous than the average Negro community in the North, the Cass County settlement not only attracted Negroes fleeing from hardships in the South but also those who had for some years unsuccessfully endeavored to establish themselves in other communities on free soil.[27]</p>
<p>These settlements were duplicated a little farther west in Illinois. Edward Coles, a Virginian, who in 1818 emigrated to Illinois, of which he later served as Governor and as liberator from slavery, settled his slaves in that commonwealth. He brought them to Edwardsville, where they constituted a community known as “Coles’ Negroes.”[28] There was another community of Negroes in Illinois in what is now called Brooklyn situated north of East St.&nbsp;Louis. This town was a center of some consequence in the thirties. It became a station of the Underground Railroad on the route to Alton and to Canada. As all of the Negroes who emerged from the South did not go farther into the North, the black population of the town gradually grew despite the fact that slave hunters captured and reenslaved many of the Negroes who settled there.[29]</p>
<p>These settlements together with favorable communities of sympathetic whites promoted the migration of the free Negroes and fugitives from the South by serving as centers offering assistance to those fleeing to the free States and to Canada. The fugitives usually found friends in Philadelphia, Columbia, Pittsburgh, Elmira, Rochester, Buffalo, Gallipolis, Portsmouth, Akron, Cincinnati, and Detroit. They passed on the way to freedom through Columbia, Philadelphia, Elizabethtown and by way of sea to New York and Boston, from which they proceeded to permanent settlements in the North.[30]</p>
<p>In the West, the migration of the blacks was further facilitated by the peculiar geographic condition in that the Appalachian highland, extending like a peninsula into the South, had a natural endowment which produced a class of white citizens hostile to the institution of slavery. These mountaineers coming later to the colonies had to go to the hills and mountains because the first comers from Europe had taken up the land near the sea. Being of the German and Scotch-Irish Presbyterian stock, they had ideals differing widely from those of the seaboard slaveholders.[31] The mountaineers believed in “civil liberty in fee simple, and an open road to civil honors, secured to the poorest and feeblest members of society.” The eastern element had for their ideal a government of interests for the people. They believed in liberty but that of kings, lords, and commons, not of all the people.[32]</p>
<p>Settled along the Appalachian highland, these new stocks continued to differ from those dwelling near the sea, especially on the slavery question.[33] The natural endowment of the mountainous section made slavery there unprofitable and the mountaineers bore it grievously that they were attached to commonwealths dominated by the radical pro-slavery element of the South, who sacrificed all other interests to safeguard those of the peculiar institution. There developed a number of clashes in all of the legislatures and constitutional conventions of the Southern States along the Atlantic, but in every case the defenders of the interests of slavery won. When, therefore, slaves with the assistance of anti-slavery mountaineers began to escape to the free States, they had little difficulty in making their way through the Appalachian region, where the love of freedom had so set the people against slavery that although some of them yielded to the inevitable sin, they never made any systematic effort to protect it.[34]</p>
<p>The development of the movement in these mountains was more than interesting. During the first quarter of the nineteenth century there were many ardent anti-slavery leaders in the mountains. These were not particularly interested in the Negro but were determined to keep that soil for freedom that the settlers might there realize the ideals for which they had left their homes in Europe. When the industrial revolution with the attendant rise of the plantation cotton culture made abolition in the South improbable, some of them became colonizationists, hoping to destroy the institution through deportation, which would remove the objection of certain masters who would free their slaves provided they were not left in the States to become a public charge.[35] Some of this sentiment continued in the mountains even until the Civil War. The highlanders, therefore, found themselves involved in a continuous embroglio because they were not moved by reactionary influences which were unifying the South for its bold effort to make slavery a national institution.[36] The other members of the mountaineer anti-slavery group became attached to the Underground Railroad system, endeavoring by secret methods to place on free soil a sufficiently large number of fugitives to show a decided diminution in the South.[37] John Brown, who communicated with the South through these mountains, thought that his work would be a success, if he could change the situation in one county in each of these States.</p>
<p>The lines along which these Underground Railroad operators moved connected naturally with the Quaker settlements established in free States and the favorable sections in the Appalachian region. Many of these workers were Quakers who had already established settlements of slaves on estates which they had purchased in the Northwest Territory. Among these were John Rankin, James Gilliland, Jesse Lockehart, Robert Dobbins, Samuel Crothers, Hugh L. Fullerton, and William Dickey. Thus they connected the heart of the South with the avenues to freedom in the North.[38] There were routes extending from this section into Ohio, Indiana, Illinois and Pennsylvania. Over the Ohio and Kentucky route culminating chiefly in Cleveland, Sandusky and Detroit, however, more fugitives made their way to freedom than through any other avenue,[39] partly too because they found the limestone caves very helpful for hiding by day. These operations extended even through Tennessee into northern Georgia and Alabama. Dillingham, Josiah Henson and Harriet Tubman used these routes to deliver many a Negro from slavery.</p>
<p>The opportunity thus offered to help the oppressed brought forward a class of anti-slavery men, who went beyond the limit of merely expressing their horror of the evil. They believed that something should be done “to deliver the poor that cry and to direct the wanderer in the right way.”[40] Translating into action what had long been restricted to academic discussion, these philanthropic workers ushered in a new era in the uplift of the blacks, making abolition more of a reality. The abolition element of the North then could no longer be considered an insignificant minority advocating a hopeless cause but a factor in drawing from the South a part of its slave population and at the same time offering asylum to the free Negroes whom the southerners considered undesirable.[4l] Prominent among those who aided this migration in various ways were Benjamin Lundy of Tennessee and James G. Birney, a former slaveholder of Huntsville, Alabama, who manumitted his slaves and apprenticed and educated some of them in Ohio.</p>
<p>This exodus of the Negroes to the free States promoted the migration of others of their race to Canada, a more congenial part beyond the borders of the United States. The movement from the free States into Canada, moreover, was contemporary with that from the South to the free States as will be evidenced by the fact that 15,000 of the 60,000 Negroes in Canada in 1860 were free born. As Detroit was the chief gateway for them to Canada, most of these refugees settled in towns of Southern Ontario not far from that city. These were Dawn, Colchester, Elgin, Dresden, Windsor, Sandwich, Bush, Wilberforce, Hamilton, St.&nbsp;Catherines, Chatham, Riley, Anderton, London, Malden and Gonfield.[42] And their coming to Canada was not checked even by request from their enemies that they be turned away from that country as undesirables, for some of the white people there welcomed and assisted them. Canadians later experienced a change in their attitude toward these refugees but these British Americans never made the life of the Negro there so intolerable as was the case in some of the free States.</p>
<p>It should be observed here that this movement, unlike the exodus of the Negroes of today, affected an unequal distribution of the enlightened Negroes.[43] Those who are fleeing from the South today are largely laborers seeking economic opportunities. The motive at work in the mind of the antebellum refugee was higher. In 1840 there were more intelligent blacks in the South than in the North but not so after 1850, despite the vigorous execution of the Fugitive Slave Law in some parts of the North. While the free Negro population of the slave States increased only 23,736 from 1850 to 1860, that of the free States increased 29,839. In the South, only Delaware, Maryland and North Carolina showed a noticeable increase in the number of free persons of color during the decade immediately preceding the Civil War. This element of the population had only slightly increased in Alabama, Kentucky, Missouri, Tennessee, Virginia, Louisiana, South Carolina and the District of Columbia. The number of free Negroes of Florida remained constant. Those of Arkansas, Mississippi and Texas diminished. In the North, of course, the migration had caused the tendency to be in the other direction. With the exception of Maine, New Hampshire, Vermont and New York which had about the same free colored population in 1860 as they had in 1850 there was a general increase in the number of Negroes in the free States. Ohio led in this respect, having had during this period an increase of 11,394.[44] A glance at the table on the accompanying page will show in detail the results of this migration.</p>
<p>STATISTICS OF THE FREE COLORED POPULATION OF THE UNITED STATES</p>
<table class="table">
<thead>
<tr class="header">
<th>State</th>
<th style="text-align: right;">Population 1850</th>
<th style="text-align: right;">Population 1860</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Alabama</td>
<td style="text-align: right;">2,265</td>
<td style="text-align: right;">2,690</td>
</tr>
<tr class="even">
<td>Arkansas</td>
<td style="text-align: right;">608</td>
<td style="text-align: right;">144</td>
</tr>
<tr class="odd">
<td>California</td>
<td style="text-align: right;">962</td>
<td style="text-align: right;">4,086</td>
</tr>
<tr class="even">
<td>Connecticut</td>
<td style="text-align: right;">7,693</td>
<td style="text-align: right;">8,627</td>
</tr>
<tr class="odd">
<td>Delaware</td>
<td style="text-align: right;">18,073</td>
<td style="text-align: right;">19,829</td>
</tr>
<tr class="even">
<td>Florida</td>
<td style="text-align: right;">932</td>
<td style="text-align: right;">932</td>
</tr>
<tr class="odd">
<td>Georgia</td>
<td style="text-align: right;">2,931</td>
<td style="text-align: right;">3,500</td>
</tr>
<tr class="even">
<td>Illinois</td>
<td style="text-align: right;">5,436</td>
<td style="text-align: right;">7,628</td>
</tr>
<tr class="odd">
<td>Indiana</td>
<td style="text-align: right;">11,262</td>
<td style="text-align: right;">11,428</td>
</tr>
<tr class="even">
<td>Iowa</td>
<td style="text-align: right;">333</td>
<td style="text-align: right;">1,069</td>
</tr>
<tr class="odd">
<td>Kentucky</td>
<td style="text-align: right;">10,011</td>
<td style="text-align: right;">10,684</td>
</tr>
<tr class="even">
<td>Louisiana</td>
<td style="text-align: right;">17,462</td>
<td style="text-align: right;">18,647</td>
</tr>
<tr class="odd">
<td>Maine</td>
<td style="text-align: right;">1,356</td>
<td style="text-align: right;">1,327</td>
</tr>
<tr class="even">
<td>Kansas</td>
<td style="text-align: right;">-</td>
<td style="text-align: right;">625</td>
</tr>
<tr class="odd">
<td>Maryland</td>
<td style="text-align: right;">74,723</td>
<td style="text-align: right;">83,942</td>
</tr>
<tr class="even">
<td>Massachusetts</td>
<td style="text-align: right;">9,064</td>
<td style="text-align: right;">9,602</td>
</tr>
<tr class="odd">
<td>Michigan</td>
<td style="text-align: right;">2,583</td>
<td style="text-align: right;">6,797</td>
</tr>
<tr class="even">
<td>Minnesota</td>
<td style="text-align: right;">-</td>
<td style="text-align: right;">259</td>
</tr>
<tr class="odd">
<td>Mississippi</td>
<td style="text-align: right;">930</td>
<td style="text-align: right;">773</td>
</tr>
<tr class="even">
<td>Missouri</td>
<td style="text-align: right;">2,618</td>
<td style="text-align: right;">3,572</td>
</tr>
<tr class="odd">
<td>New Hampshire</td>
<td style="text-align: right;">520</td>
<td style="text-align: right;">494</td>
</tr>
<tr class="even">
<td>New Jersey</td>
<td style="text-align: right;">23,810</td>
<td style="text-align: right;">25,318</td>
</tr>
<tr class="odd">
<td>New York</td>
<td style="text-align: right;">49,069</td>
<td style="text-align: right;">49,005</td>
</tr>
<tr class="even">
<td>North Carolina</td>
<td style="text-align: right;">27,463</td>
<td style="text-align: right;">30,463</td>
</tr>
<tr class="odd">
<td>Ohio</td>
<td style="text-align: right;">25,279</td>
<td style="text-align: right;">36,673</td>
</tr>
<tr class="even">
<td>Oregon</td>
<td style="text-align: right;">-</td>
<td style="text-align: right;">128</td>
</tr>
<tr class="odd">
<td>Pennsylvania</td>
<td style="text-align: right;">53,626</td>
<td style="text-align: right;">56,949</td>
</tr>
<tr class="even">
<td>Rhode Island</td>
<td style="text-align: right;">3,670</td>
<td style="text-align: right;">3,952</td>
</tr>
<tr class="odd">
<td>South Carolina</td>
<td style="text-align: right;">8,960</td>
<td style="text-align: right;">9,914</td>
</tr>
<tr class="even">
<td>Tennessee</td>
<td style="text-align: right;">6,422</td>
<td style="text-align: right;">7,300</td>
</tr>
<tr class="odd">
<td>Texas</td>
<td style="text-align: right;">397</td>
<td style="text-align: right;">355</td>
</tr>
<tr class="even">
<td>Vermont</td>
<td style="text-align: right;">718</td>
<td style="text-align: right;">709</td>
</tr>
<tr class="odd">
<td>Virginia</td>
<td style="text-align: right;">54,333</td>
<td style="text-align: right;">58,042</td>
</tr>
<tr class="even">
<td>Wisconsin</td>
<td style="text-align: right;">635</td>
<td style="text-align: right;">1,171</td>
</tr>
<tr class="odd">
<td><strong>Territories:</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td>Colorado</td>
<td style="text-align: right;">-</td>
<td style="text-align: right;">46</td>
</tr>
<tr class="odd">
<td>Dakota</td>
<td style="text-align: right;">-</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td>District of Columbia</td>
<td style="text-align: right;">10,059</td>
<td style="text-align: right;">11,131</td>
</tr>
<tr class="odd">
<td>Minnesota Territory</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">-</td>
</tr>
<tr class="even">
<td>Nebraska</td>
<td style="text-align: right;">-</td>
<td style="text-align: right;">67</td>
</tr>
<tr class="odd">
<td>Nevada</td>
<td style="text-align: right;">-</td>
<td style="text-align: right;">45</td>
</tr>
<tr class="even">
<td>New Mexico</td>
<td style="text-align: right;">207</td>
<td style="text-align: right;">85</td>
</tr>
<tr class="odd">
<td>Oregon Territory</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">-</td>
</tr>
<tr class="even">
<td>Utah</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="odd">
<td>Washington</td>
<td style="text-align: right;">-</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td style="text-align: right;">434,495</td>
<td style="text-align: right;">488,070</td>
</tr>
</tbody>
</table>
<p>[Footnote 8: <em>Southern Workman</em>, xxxvii, p.&nbsp;157.]</p>
<p>[Footnote 9: Levi Coffin, <em>Reminiscences</em>, chaps, i and ii.]</p>
<p>[Footnote 10: <em>Southern Workman</em>, xxxvii, pp.&nbsp;161-163.]</p>
<p>[Footnote 11: Coffin, <em>Reminiscences</em>, p.&nbsp;109; and Howe’s <em>Historical Collections</em>, p.&nbsp;356.]</p>
<p>[Footnote 12: <em>Southern Workman</em>, xxxvii, pp.&nbsp;162, 163.]</p>
<p>[Footnote 13: Levi Coffin, <em>Reminiscences</em>, pp.&nbsp;108-111.]</p>
<p>[Footnote 14: Siebert, <em>The Underground Railroad</em>, p.&nbsp;249.]</p>
<p>[Footnote 15: Langston, <em>From the Virginia Plantation to the National Capitol</em>, p.&nbsp;35.]</p>
<p>[Footnote 16: Howe, <em>Historical Collections</em>, p.&nbsp;465.]</p>
<p>[Footnote 17: <em>History of Brown County, Ohio</em>, p.&nbsp;313.]</p>
<p>[Footnote 18: Wattles said: he purchased for himself 190 acres of land, to establish a manual labor school for colored boys. He had maintained a school on it, at his own expense, till the eleventh of November, 1842. While in Philadelphia the winter before, he became acquainted with the trustees of the late Samuel Emlen, a Friend of New Jersey. He left by his will $20,000 for the “support and education in school learning and the mechanic arts and agriculture, boys, of African and Indian descent, whose parents would give them up to the school. They united their means and purchased Wattles farm, and appointed him the superintendent of the establishment, which they called the Emlen Institute.”–See Howe’s <em>Historical Collections</em>, p.&nbsp;356.]</p>
<p>[Footnote 19: Howe’s <em>Historical Collections</em>, p.&nbsp;355.]</p>
<p>[Footnote 20: <em>Manuscripts</em> in the possession of J.E. Moorland.]</p>
<p>[Footnote 21: <em>The African Repository</em>, xxii, pp.&nbsp;322, 333.]</p>
<p>[Footnote 22: Simmons, <em>Men of Mark</em>, p.&nbsp;723.]</p>
<p>[Footnote 23: <em>Southern Workman</em>, xxxvii, p.&nbsp;158.]</p>
<p>[Footnote 24: <em>The Journal of Negro History</em>, I, pp.&nbsp;23-33.]</p>
<p>[Footnote 25: <em>Ibid</em>., I, p.&nbsp;26.]</p>
<p>[Footnote 26: <em>The African Repository</em>, passim.]</p>
<p>[Footnote 27: Although constituting a majority of the population even before the Civil War the Negroes of this township did not get recognition in the local government until 1875 when John Allen, a Negro, was elected township treasurer. From that time until about 1890 the Negroes always shared the honors of office with their white citizens and since that time they have usually had entire control of the local government in that township, holding such offices as supervisor, clerk, treasurer, road commissioner, and school director. Their record has been that of efficiency. Boss rule among them is not known. The best man for an office is generally sought; for this is a community of independent farmers. In 1907 one hundred and eleven different farmers in this community had holdings of 10,439 acres. Their township usually has very few delinquent taxpayers and it promptly makes its returns to the county.–See the <em>Southern Workman</em>, xxxvii, pp.&nbsp;486-489.]</p>
<p>[Footnote 28: Davidson and Stowe, <em>A Complete History of Illinois</em>, pp.&nbsp;321, 322; and Washburn, <em>Edward Coles</em>, pp.&nbsp;44 and 53.]</p>
<p>[Footnote 29: The Negro population of this town so rapidly increased after the war that it has become a Negro town and unfortunately a bad one. Much improvement has been made in recent years.–See <em>Southern Workman</em>, xxxvii, pp.&nbsp;489-494.]</p>
<p>[Footnote 30: Still, <em>Underground Railroad</em>, passim; Siebert, <em>Underground Railroad</em>, pp.&nbsp;34, 35, 40, 42, 43, 48, 56, 59, 62, 64, 70, 145, 147; Drew, <em>Refugee</em>, pp.&nbsp;72, 97, 114, 152, 335 and 373.]</p>
<p>[Footnote 31: <em>The Journal of Negro History</em>, I, pp.&nbsp;132-162.]</p>
<p>[Footnote 32: <em>Ibid</em>., I, 138.]</p>
<p>[Footnote 33: Olmsted, <em>Back Country</em>, p.&nbsp;134.]</p>
<p>[Footnote 34: In the Appalachian mountains, however, the settlers were loath to follow the fortunes of the ardent pro-slavery element. Actual abolition, for example, was never popular in western Virginia, but the love of the people of that section for freedom kept them estranged from the slaveholding districts of the State, which by 1850 had completely committed themselves to the pro-slavery propaganda. In the Convention of 1829-30 Upshur said there existed in a great portion of the West (of Virginia) a rooted antipathy to the slave. John Randolph was alarmed at the fanatical spirit on the subject of slavery, which was growing in Virginia,–See the <em>Journal of Negro History</em>, I, p.&nbsp;142.]</p>
<p>[Footnote 35: Adams, <em>Neglected Period of Anti-Slavery</em>.]</p>
<p>[Footnote 36: <em>The Journal of Negro History</em>, I, pp.&nbsp;132-160.]</p>
<p>[Footnote 37: Siebert, <em>Underground Railroad</em>, p.&nbsp;166.]</p>
<p>[Footnote 38: Adams, <em>Neglected Period of Anti-Slavery</em>.]</p>
<p>[Footnote 39: Siebert, <em>Underground Railroad</em>, chaps. v and vi.]</p>
<p>[Footnote 40: <em>An Address to the People of North Carolina on the Evils of Slavery.</em>]</p>
<p>[Footnote 41: Washington, <em>Story of the Negro</em>, I, chaps. xii, xiii and xiv. ]</p>
<p>[Footnote 42: <em>Father Henson’s Story of his own Life</em>, p.&nbsp;209; Coffin, <em>Reminiscences</em>, pp.&nbsp;247-256; Howe, <em>The Refugees from Slavery</em>, p.&nbsp;77; Haviland, <em>A Woman’s Work</em>, pp.&nbsp;192, 193, 196.]</p>
<p>[Footnote 43: Woodson, <em>The Education of the Negro Prior to 1861</em>, pp.&nbsp;236-240.]</p>
<p>[Footnote 44: <em>The United States Censuses of 1850 and 1860.</em>]</p>


<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Moore, <em>Anti-Slavery</em>, p.&nbsp;79; and <em>Special Report of the United States Commissioner of Education</em>, 1871, p.&nbsp;376; Weeks, <em>Southern Quakers</em>, pp.&nbsp;215, 216, 231, 230, 242.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p><em>The Southern Workman</em>, xxvii, p.&nbsp;161.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Rhodes, <em>History of the United States</em>, chap.&nbsp;i, p.&nbsp;6; Bancroft, <em>History of the United States</em>, chap.&nbsp;ii, p.&nbsp;401; and Locke, <em>Anti-Slavery</em>, p.&nbsp;32.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p><em>A Brief Statement of the Rise and Progress of the Testimony of the Quakers</em>, passim; Woodson, <em>The Education of the Negro Prior to 1861</em>, p.&nbsp;43.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Woodson, <em>The Education of the Negro Prior to 1861</em>, p.&nbsp;44; and Locke, <em>Anti-Slavery</em>, p.&nbsp;32.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p><em>The Southern Workman</em>, xxxvii, pp.&nbsp;158-169.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Turner, <em>The Negro in Pennsylvania</em>, pp.&nbsp;144, 145, 151, 155.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/chapter-01.html" class="pagination-link  aria-label=" &lt;span="" a="" place="" of="" refuge&lt;="" span&gt;"="">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Finding a Place of Refuge</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/chapter-03.html" class="pagination-link" aria-label="<span class='chapter-number'>3</span>&nbsp; <span class='chapter-title'>Fighting It Out on Free Soil</span>">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Fighting It Out on Free Soil</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>